on: 
  push:
    paths:
      - "asoul.md"
  pull_request:
    paths:
      - "asoul.md"

name: "目录生成"
jobs:
  generateTOC:
    name: generate toc
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/toc-generator@v4
        with:
          TOC_TITLE: "点击展开"
          CREATE_PR: true
          COMMIT_MESSAGE: "生成目录索引"
          COMMIT_NAME: avimitin
          COMMIT_EMAIL: avimitin@gmail.com
          FOLDING: true
          TARGET_PATHS: "asoul.md"
